runner: !BuilderRunner
  prometheus_host: "10.239.157.129:9090"
  cycle:    # default 3600s
  time_range:    # defult 86400 seconds
  step:    # prometheus sample step, default 10 seconds
  timeout:     # prometheus request timeout, default 1 seconds
  database: !ModelDatabase
    db_type: etcd    # 1) local 2)zookeeper 3)etcd
    directory: ~     # required for local
    host: "10.239.157.129:2379"     # required for zookeeper and etcd
    namespace: ~     # for zookeeper, if none, using default model_distribution
    ssl_verify: false     # for etcd, default false
    api_path: "/v3beta"     # for etcd, '/v3alpha' for 3.2.x etcd version, '/v3beta' or '/v3' for 3.3.x etcd version
    timeout: 5.0     # for etcd, default 5.0 seconds
    client_cert_path: ~    # for etcd, default None
    client_key_path: ~     # for etcd, default None
  model: !DistriModel
    span: 3
    strict: false
    use_origin: false
    verbose: false