runner: !DetectionRunner
  node: !MesosNode
    mesos_agent_endpoint: "http://127.0.0.1:5051"
  action_delay: &action_delay 1.
  metrics_storage: !LogStorage
    output_filename: '/tmp/metrics.prom'
    overwrite: true
  anomalies_storage: !LogStorage
    output_filename: '/tmp/anomalies.prom'
    overwrite: true
  detector: !ContentionDetector
    database: !ModelDatabase
        db_type: etcd    # 1) local 2)zookeeper 3)etcd
        directory: ~     # required for local
        host: "10.239.157.129:2379"     # required for zookeeper and etcd
        namespace: ~     # for zookeeper, if none, using default model_distribution
        ssl_verify: false     # for etcd, default false
        api_path: "/v3beta"     # for etcd, '/v3alpha' for 3.2.x etcd version, '/v3beta' or '/v3' for 3.3.x etcd version
        timeout: 5.0     # for etcd, default 5.0 seconds
        client_cert_path: ~    # for etcd, default None
        client_key_path: ~     # for etcd, default None
    action_delay: *action_delay
  # if agg_period value is multiple times of action_delay, prm will aggregate metrics based on agg_period
  # or it will record metrics based on action_delay
    agg_period: 20.
    model_pull_cycle: 180.  # how many cycles needs to be waited after previous model pulling, default 180 cycles
  # prm will detect contention base on the rdt. This configuration must be enabled.
  rdt_enabled: True
  # key value pairs to tag the data
  extra_labels:
    env_uniq_id: "120"
    own_ip: "10.3.88.120"

