runner: !AllocationRunner
  rdt_enabled: True
  node: !MesosNode
    mesos_agent_endpoint: "http://127.0.0.1:5051"
  action_delay: &action_delay 1.
  metrics_storage: !LogStorage
    output_filename: 'metrics/metrics.prom'
    overwrite: true
  anomalies_storage: !LogStorage
    output_filename: 'metrics/anomalies.prom'
    overwrite: true
  allocations_storage: !LogStorage
    output_filename: 'metrics/allocations.prom'
    overwrite: true
  allocator: !ResourceAllocator
    action_delay: *action_delay
    mode_config: 'detect'
    agg_period: 20.
    exclusive_cat: False
    database: !ModelDatabase
      db_type: etcd    # 1) local 2)zookeeper 3)etcd
      directory: ~     # required for local
      host: "10.239.157.129:2379"     # required for zookeeper and etcd
      namespace: ~     # for zookeeper, if none, using default model_distribution
      ssl_verify: false     # for etcd, default false
      api_path: "/v3beta"     # for etcd, '/v3alpha' for 3.2.x etcd version, '/v3beta' or '/v3' for 3.3.x etcd version
      timeout: 5.0     # for etcd, default 5.0 seconds
      client_cert_path: ~    # for etcd, default None
      client_key_path: ~     # for etcd, default None
    model_pull_cycle: 180.
  extra_labels:
    env_uniq_id: "15"
    own_ip: "100.64.176.15"
